app = "god-bless-this-bot"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "mad"

[deploy]
strategy = "immediate"

[env]
PORT = "8080"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]