# fly.toml app configuration file generated for god-bless-this-bot on 2025-04-22T13:38:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'god-bless-this-bot'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[deploy]
  strategy = 'immediate'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
