name: Deploy Bot with Terraform

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Fly.io Docker registry
        run: |
          echo "${{ secrets.FLY_API_TOKEN }}" | docker login registry.fly.io -u x-access-token --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest .
          docker push registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        env:
          TF_API_TOKEN: ${{ secrets.TF_TOKEN }}
        run: terraform init

      - name: Terraform Apply
        env:
          TF_API_TOKEN: ${{ secrets.TF_TOKEN }}
          TF_VAR_fly_token: ${{ secrets.FLY_API_TOKEN }}
          TF_VAR_telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TF_VAR_fly_app: "god-bless-this-bot"
        run: terraform apply -auto-approve

      - name: Notify Telegram
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="Me he actualizado correctamente desde GitHub Actions!" \
            -d parse_mode=Markdown
